[package]
name = "weiqi_pattern_search_server"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.1"
weiqi_pattern = { git = "https://github.com/ddgos/weiqi_pattern", version = "0.1.0" }
